services:
  app:
    image: lscr.io/linuxserver/healthchecks:latest
    restart: unless-stopped
    volumes:
      - app_config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SITE_NAME="Cronjob Monitoring"
      - SITE_URL
      - SUPERUSER_EMAIL
      - SUPERUSER_PASSWORD
    networks:
      proxy_apps:

networks:
  proxy_apps:
    name: proxy_apps
    external: true