services:
  app:
    image: lscr.io/linuxserver/healthchecks:latest
    restart: unless-stopped
    volumes:
      - app_config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SITE_NAME="Cronjob Monitoring"
      - SITE_ROOT
      - SUPERUSER_EMAIL
      - SUPERUSER_PASSWORD
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - ADMINS=${SUPERUSER_EMAIL}
      - SERVER_EMAIL=${SUPERUSER_EMAIL}
      - REGISTRATION_OPEN=False
      - SITE_LOGO_URL
    networks:
      proxy_apps:

volumes:
  app_config:

networks:
  proxy_apps:
    name: proxy_apps
    external: true